### ISSUE TITLE
Transition of Zephyr project into MicroROS

### ISSUE THREAD

**Issue by eden-desta** [micro-ROS/zephyr_apps#33]
Hello!

I have been working heavily in Zephyr last few months trying to get up to speed on the different aspects and options they provide. 
Recently I have been experimenting with their CANopen example that they provide out of the box can be found in their example section.

My question is how do I transition that entire project into MicroROS?
I'm having trouble with includes and I was wondering if there was a formalized procedure i can potentially follow to understand what to do with the Kconfigs or the prj.conf files etc. 

Look forward to your response! Thank you!!!!!!

**Comment by ralph-lange** [comment]
Hello , 
That’s an interesting project. My first guess is that it has to be split up: Basic CAN support should go into the Micro-XRCE-DDS middleware whereas the different threads (CAN receive thread, timer interval thread, mainline thread) could be implemented on the rclc level using ROS timers and guard conditions. Or do you want to bring the existing code simply into the micro-ROS build system?
There are a couple of other micro-ROS users who are interested in CAN support for Micro-XRCE-DDS. As I understood, there are already even two prototypes (but not open-sourced yet). You may join the discussion at https://micro-ros.slack.com/ -> micro-ros-can-transport channel. Also, we could reserve a slot at one of the next Embedded WG meetings for a discussion on CAN support for micro-ROS.
// Cc @pablogs9, @jamoralp, @FranFin

**Comment by pablogs9** [comment]
Hello @edesta-be regarding the transition of an existing project to micro-ROS, have you seen [our example of integrating micro-ROS in a Zephyr project](https://github.com/micro-ROS/micro_ros_zephyr_module)?

I'm not sure if this solves your question, but in the case that you want to add micro-ROS to your Zephyr project just check the `module/libmicroros`. This way you will integrate micro-ROS into Zephyr instead of integrating your Zephyr application inside the micro-ROS build system.

Does this solve your doubts?

**Comment by FranFin** [comment]
Hi all. I'll add a section dedicated to CAN support in micro-ROS to next [EWG meeting agenda](https://docs.google.com/document/d/1hGxwpuHDPCyEYHBCd5IIgvoFGJgkC5WKI12ghEfqwXg/edit?usp=sharing) (meeting time: Wednesday the 3rd of Feb, at 5pm CET). @edesta-be you're very welcome to participate so as to share with us and the rest of the community your issue!

**Comment by eden-desta** [comment]
Wow thank you so much folks! I appreciate this! I will try and make the meeting! 
@pablogs9  ill take a look at that example I think that will immensely help vs the approach i am taking!

**Comment by pablogs9** [comment]
Cool, please close when you are ok with the approach. Thanks!
