### ISSUE TITLE
MicroROS not running as expected

### ISSUE THREAD

**Issue by eden-desta** [micro-ROS/zephyr_apps#36]
Hello!
So this is super new -- and kind of strange. 
My setup runs through the expected build process of what we need to do in order to build the firmware, flash it etc and then run the agent. 

However, when i run the agent its stuck:
```
[1612884194.563610] info     | TermiosAgentLinux.cpp | init                     | running...             | fd: 3
[1612884194.563954] info     | Root.cpp           | set_verbose_level        | logger setup           | verbose_level: 6
```

I thought perhaps, i broke something in my own code (i was running using custom application). So i built another microros environment and tried to run the int32 publisher and the board was still stuck. 

Is there anything that could be doing this?
I just repulled the micro_ros_setup this morning and had not updated in over a month please let me know what your thoughts are!

Thank you!

**Comment by pablogs9** [comment]
Hello @edesta-be just this morning we have been updating critical sections of the codebase... 

Could you retry the micro-ROS installation from scratch with the current state of the repos? If it does not work, could you please share with us some steps for replicating your situation?

**Comment by eden-desta** [comment]
For sure! I'll do so right now!

**Comment by eden-desta** [comment]
For a completely blank start: 
```
source /opt/ros/foxy/setup.bash
mkdir microros_ws
cd microros_ws
git clone -b foxy https://github.com/micro-ROS/micro_ros_setup.git src/micro_ros_setup

sudo apt update && rosdep update
rosdep install --from-path src --ignore-src -y

colcon build
. install/setup.bash

ros2 run micro_ros_setup create_firmware_ws.sh zephyr nucleo_f746zg

ros2 run micro_ros_setup configure_firmware.sh int32_publisher --transport serial --dev 3

ros2 run micro_ros_setup build_firmware.sh
ros2 run micro_ros_setup flash_firmware.sh

ros2 run micro_ros_setup create_agent_ws.sh
ros2 run micro_ros_setup build_agent.sh
. install/setup.bash

ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/serial/by-id/usb-STMicroelectronics_STM32_STLink_066FFF343039564157223210-if02 -v6
```

So same thing happens when i do this:
```
[1612885643.066215] info     | TermiosAgentLinux.cpp | init                     | running...             | fd: 4
[1612885643.066430] info     | Root.cpp           | set_verbose_level        | logger setup           | verbose_level: 6
```
It doesnt move past this point. 
I have pressed the RESET button on the board and tried flashing again. It doesnt work. 
This is for the int32_publisher using nucleo_f746zg. 
But I imagine if you dont have this board the same problem likely exists with the olimex.

I can try this again with another f7 board and see if it is potentially a hardware problem

**Comment by eden-desta** [comment]
Yes,
so new board -- i didnt go through the entire build process because that would have been unnecessary 
just flashed it and tried running the agent again

```
ros2 run micro_ros_setup flash_firmware.sh
ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/serial/by-id/usb-STMicroelectronics_STM32_STLink_066CFF343937424257252920-if02 -v6
```

It is definitely flashing it because i see the LED going off but the agent is still stuck on the startup two messages.

**Comment by pablogs9** [comment]
Try to use UART0 or change [this](https://github.com/micro-ROS/zephyr_apps/blob/2557814c132e9865429471a04024ad682afb1daf/microros_extensions/microros_transports.h#L46), we have refactored the transports and I forgot to take into account the micro_ros_setup configuration...

Tomorrow I will check this again, let me know if this solution works.

**Comment by eden-desta** [comment]
Nice!
I changed the [extension](https://github.com/micro-ROS/zephyr_apps/blob/2557814c132e9865429471a04024ad682afb1daf/microros_extensions/microros_transports.h#L46) to 3 and it worked! Nice 

Thank you! 
Feel free to close this but in case you need it open to track i will leave it up to you! Thank you.

Let me know if you need me to test with your updates as well will be happy to help anyway I can!

**Comment by eden-desta** [comment]
It actually still exists with the custom application -- I'm going to revert my changes to the state of the software I previously had running and test it with a clean build

**Comment by pablogs9** [comment]
Hello @edesta-be, I'm closing this. Feel free to reopen if you have further problems!
