### ISSUE TITLE
Add sensor from pure zephyr project into microros zephyr

### ISSUE THREAD

**Issue by MARLARCHAN** [micro-ROS/zephyr_apps#41]
Dear @pablogs9 

   I'm trying to add adxl372 sensor from pure zephyr  project into microROS zephyr. In there, where can I add .overlay file from zephyrproject/zephyr/ samples/sensors/board/ into microROS zephyr_apps? Please suggest me about it.

Best Regards,
Marlar

**Comment by pablogs9** [comment]
Here you have an example: https://github.com/micro-ROS/zephyr_apps/tree/foxy/apps/tof_ws2812

Inside the `board` folder
