### ISSUE TITLE
ROS2 Topics Not visible

### ISSUE THREAD

**Issue by manuaatitya** [micro-ROS/zephyr_apps#42]
## ROS2 Topics Not visible

- Hardware description: STM Nucleo H743ZI
- RTOS: Zephyr RTOS
- ROS: ROS2 foxy

#### Steps to reproduce the issue
Hi, I'm using a custom Zephyr App to control a motor connected to the STM Nucleo H743ZI board using the PWM pins via a serial port. (Note: I'm using the microROS application in a docker container)

I've followed the steps as per the official MicroROS tutorial "[First Application RTOS](https://micro.ros.org/docs/tutorials/core/first_application_rtos/)". 

I'm also attaching the [src/main](https://pastebin.com/RnhG9AXw) file for reference.

Additional overlay files are not required as I'm using the already configured PWM_12 pin in the board.

#### Actual behavior
The configure steps works fine and the output is as follows:
![configure](https://user-images.githubusercontent.com/32318187/115202954-8eac3380-a114-11eb-90a8-5e65d038fee8.PNG)

The code builds without any errors. 

There is no error in the flashing stage as well:
![flash](https://user-images.githubusercontent.com/32318187/115203110-b9968780-a114-11eb-9177-1b8e9ba3d14b.PNG)

However on execution of the microROS agent, no message is getting printed on the terminal:
![run](https://user-images.githubusercontent.com/32318187/115203364-ffebe680-a114-11eb-91b4-ab467f54b7fe.PNG)

And the ROS topics list is also empty as shown below:
![topic_list](https://user-images.githubusercontent.com/32318187/115203388-04b09a80-a115-11eb-88f8-36287cdcee4f.PNG)

Any help would be appreciated to resolve this issue.
Thanks in advance.

**Comment by pablogs9** [comment]
Your micro-ROS client is not connecting to the agent. Please use `-v6` in the agent for verbose output.

Are you setting the serial port that the micro-ROS client should use [here](https://github.com/micro-ROS/zephyr_apps/blob/89e85c8cf29647d276203735a49a41ecbc4b8dd1/microros_extensions/microros_transports.h#L47)?

**Comment by pablogs9** [comment]
Also, remember to init the transports: https://github.com/micro-ROS/zephyr_apps/blob/89e85c8cf29647d276203735a49a41ecbc4b8dd1/apps/int32_publisher/src/main.c#L32

**Comment by manuaatitya** [comment]
Hi @pablogs9,
Thanks for the reply,

I'd forgot to init the transports previously, now that I've added that part, the publishers, subscribers and topics are getting created properly, however, I'm not able to send/receive data over the serial port. 

As you pointed out maybe, I've to try different settings for the default_zephyr_transport parameter

**Comment by pablogs9** [comment]
Ok, I'm closing since solved. Please reopen if you have any other issues.
