### ISSUE TITLE
ROS Topics Not Publishing Data

### ISSUE THREAD

**Issue by manuaatitya** [micro-ROS/zephyr_apps#43]
## ROS Topics Not Publishing Data

- Hardware description: STM Nucleo H743ZI
- RTOS: RTOS: Zephyr RTOS
- ROS: ROS2 foxy

Hi, I'm using a custom Zephyr App similar to the [int32_publisher package](https://github.com/micro-ROS/zephyr_apps/tree/foxy/apps/int32_publisher) to publish integer data to the STM Nucleo H743ZI board via a serial port. (Note: I'm using the microROS application in a docker container)

However, the ros topics don't seem to receive or send any data when the ros2 topics echo command is used as shown below:
![run_1](https://user-images.githubusercontent.com/32318187/115401438-05762900-a208-11eb-942f-d9928a4ba0fc.PNG)

#### Steps to reproduce the issue
The [source file](https://pastebin.com/yqN6dgDJ) that I used is also attached for your reference. In fact, I've just modified the msg data to some fixed value instead of incrementing on each timestep as in the [int32_publisher package](https://github.com/micro-ROS/zephyr_apps/tree/foxy/apps/int32_publisher/src/main.c).

As suggested in the [Issue](https://github.com/micro-ROS/zephyr_apps/issues/36), the [default zephyr transport parameter](https://github.com/micro-ROS/zephyr_apps/blob/89e85c8cf29647d276203735a49a41ecbc4b8dd1/microros_extensions/microros_transports.h#L47) has also modified to others values of 1, 2 & 3 from the default 0 value and still no data is being sent/ received in the serial port as verified by connecting minicom to the serial port. (The pin configurations has also been verified to be error-free).

The log file on executing the ros2 run micro_ros_agent micro_ros_agent serial --dev <device name> is command is [error_log](https://pastebin.com/2nxFNUAJ).

Any help to resolve the issue would be appreciated.
Thanks in advance.

**Comment by pablogs9** [comment]
It seems that your micro-ROS client is connecting well to the agent in the screenshot, so maybe have you tried to do the `rcl_publish(&publisher, &msg, NULL)` inside the main loop? Let me know if this works so we can see if this is a middleware issue or an executor issue.

**Comment by manuaatitya** [comment]
Hi @pablogs9, I tried the following as you suggested, 
- I added the ```rcl_publish(&publisher, &msg, NULL)``` inside the main loop but not inside the while(1) loop as in the [src file](https://pastebin.com/L9U1MWjL)
- It's printing the data once onto the terminal as seen in the figure:
![1time_print](https://user-images.githubusercontent.com/32318187/115423810-c225b580-a21b-11eb-8420-7ceb3cad7d02.PNG)

However, if I add the ```rcl_publish(&publisher, &msg, NULL)``` inside the main loop and within the while(1) loop, nothing is getting printed onto the log

**Comment by pablogs9** [comment]
Let me know if this works:

```c
    msg.data = 1300;
    
    while(1){
        rcl_publish(&publisher, &msg, NULL);  // ------------------------------------------------------- Added this here
        k_sleep(K_SECONDS(SLEEP_TIME_S));
    }
```

In any case, are you sure that this `return` inside the PWM set the main loop is not reached at any moment?

**Comment by manuaatitya** [comment]
Hi @pablogs9 , the  ```rcl_publish(&publisher, &msg, NULL);``` code works but as mentioned sometimes the return statement is reached in the main loop and hence causing issues. 
If I comment out the return in the main code, the publisher is publishing the data correctly. 

On closer debugging, I found that we are facing a PWM issue similar to the one described in this [link](https://github.com/zephyrproject-rtos/zephyr/issues/26607), the solution for which is deprecated now. 
I couldn't debug the PWM error sooner because nothing was printed to the terminal/serial output despite using print statements in case of errors.


Thanks a lot for the help so far.

**Comment by manuaatitya** [comment]
Hi @pablogs9,

I face the same issue when i use a custom message to publish data to a ROS Topic. My,

    ros2 topic echo /topicName 
gives no output when i use a custom message type however, rostopic echo /topicName displays output if i use a standard message type.

Kindly help me resolve the issue,

Any help to resolve the issue will be appreciated.

**Comment by pablogs9** [comment]
Is this related to micro-ROS?

**Comment by manuaatitya** [comment]
Hi @pablogs9, yes this issue is a continuation of my original question.

**Comment by pablogs9** [comment]
I don't understand the issue, mainly because `rostopic` is a ROS 1 tool and micro-ROS work with ROS 2.

**Comment by manuaatitya** [comment]
> I don't understand the issue, mainly because `rostopic` is a ROS 1 tool and micro-ROS work with ROS 2.

Hi @pablogs9, 
     Sorry for the typo in the comment, I meant ros2 topic echo only.

**Comment by pablogs9** [comment]
Can you share you micro-ROS client code and the micro-ROS agent output in this new case?

**Comment by manuaatitya** [comment]
My [micro-ros source code](https://pastebin.com/qsZZH9Lz) is as attached in the link. I'm using a custom message type "pwm_motor_values" which has basically 4 int values to control motor pwm values. (The custom message type builds without errors). 

I donot have access to my remote machine now but the output is exactly similar to the image that I had posted in my first comment as attached below. I'm also sending the exact output soon.

> However, the ros topics don't seem to receive or send any data when the ros2 topics echo command is used as shown below:
> ![run_1](https://user-images.githubusercontent.com/32318187/115401438-05762900-a208-11eb-942f-d9928a4ba0fc.PNG)


Thanks in advance.

**Comment by pablogs9** [comment]
Can you share the `.msg` for your custom type?

**Comment by manuaatitya** [comment]
I followed this [tutorial](https://micro.ros.org/docs/tutorials/advanced/create_new_type/) to create a new custom message and the contents of my .msg file is as follows

    uint32 pwm_motor1_pwm_value
    uint32 pwm_motor2_pwm_value
    uint32 pwm_motor3_pwm_value
    uint32 pwm_motor4_pwm_value

**Comment by pablogs9** [comment]
Is the `timer_callback` being executed? can you add a debug trace there and check if the executor is running the timer correctly?

**Comment by manuaatitya** [comment]
Hi @pablogs9, 
    I couldn't check if the timer_callback is being executed. (I tried printing some values on to the terminal but since the log is like serialised data (I'm not exactly sure of the data), I couldn't exactly check if the message is getting printed correctly).

However, this issue exists even if try out the prebuilt apps like ping_pong, int32_publisher. 
Upon build, flash and execution, I'm not able to see the ros2 topics and the ros2 topic list doesn't print anything.

![Selection_040](https://user-images.githubusercontent.com/32318187/124079616-ff51c380-da66-11eb-9a9b-03b44a7997e7.png)

The microros agent seems to be working fine though ...
![Selection_039](https://user-images.githubusercontent.com/32318187/124079629-04af0e00-da67-11eb-8eb8-dc12ecdaffc4.png)
