### ISSUE TITLE
add_two_ints_service not working on Galactic

### ISSUE THREAD

**Issue by branilson** [micro-ROS/zephyr_apps#47]
## Issue template

- Hardware description: blackpill_f411ce and blackpill_f401ce
- RTOS: Zephyr
- Installation type: transport serial-usb
- Version or commit hash: Galactic

#### Steps to reproduce the issue
As the boards I am using are not listed at the CMakelist.txt, I've added them manually. Since it is done, It builds, flashes, and connects with the Agent OK.

#### Expected behavior
Service responds to a proper service call.

#### Actual behavior
As soon as the first service call is sent, the service freezes, and no response is sent back.

#### Additional information
I did the same tests with Foxy and the service works alright. BTW, the other publisher/subscriber demos works fine, even in Galactic. The only issue is with the service demo.
![zephyr_apps_service_issue](https://user-images.githubusercontent.com/10917766/144101242-a6cfda59-0923-4abf-a419-1be5d51b98b4.png)

**Comment by pablogs9** [comment]
Working on that

**Comment by Acuadros95** [comment]
Are you using Fast-DDS as your ROS middleware? Its not installed by default on galactic and its needed to use micro-ROS services.

To install it:
`sudo apt install ros-galactic-rmw-fastrtps-cpp`

And to activate it on each terminal:
`export RMW_IMPLEMENTATION=rmw_fastrtps_cpp`

**Comment by branilson** [comment]
@Acuadros95, it worked with Fast-DDS. Thank you. I think it should be informed somewhere in the tutorials.
